# Generated by Django 5.0.3 on 2024-04-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserv_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(error_messages={'required': 'Ce champ est requis.'}, max_length=100)),
                ('nbre_person', models.IntegerField(error_messages={'required': 'Ce champ est requis.'})),
                ('date', models.DateField(error_messages={'required': 'Ce champ est requis.'})),
                ('heure', models.TimeField(error_messages={'required': 'Ce champ est requis.'})),
                ('email', models.EmailField(error_messages={'required': 'Ce champ est requis.'}, max_length=254)),
                ('telephone', models.CharField(error_messages={'required': 'Ce champ est requis.'}, max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'En attente'), ('Accepted', 'Acceptée'), ('Rejected', 'Rejetée')], default='Pending', max_length=10)),
            ],
        ),
    ]
