# Generated by Django 5.0.3 on 2024-04-08 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.reserv_model'),
        ),
    ]
